apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cpol01-require-labels
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: check-for-labels-cpol
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "The label `app.kubernetes.io/name` is required."
      pattern:
        metadata:
          labels:
            app.kubernetes.io/name: "?*"
