apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: nspol01-require-labels
  namespace: test
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: check-for-labels-nspol
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "The label `app.kubernetes.io/name` is required."
      pattern:
        metadata:
          labels:
            app.kubernetes.io/name: "?*"
